"use client"

import { getWCAGStats, wcagCriteria } from "@/lib/wcag-data"
import * as XLSX from "xlsx"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { FileSpreadsheet, Download, ArrowLeft, CheckCircle } from "lucide-react"
import Link from "next/link"

export default function WCAGExcelDownload() {
  const stats = getWCAGStats()

  const downloadExcelTemplate = () => {
    try {
      // Main checklist data with proper formatting
      const checklistData = wcagCriteria.map((criterion, index) => ({
        'Row #': index + 1,
        'SC Number': criterion.number,
        'Success Criterion': criterion.title,
        'Level': criterion.level,
        'Principle': criterion.principle,
        'Guideline': criterion.guideline,
        'Description': criterion.description,
        'Status': 'NOT COMPLETED',
        'Completion Date': '',
        'Notes': '',
        'Priority': criterion.level === 'AA' ? 'HIGH' : criterion.level === 'A' ? 'MEDIUM' : 'LOW'
      }))

      // Create main worksheet
      const worksheet = XLSX.utils.json_to_sheet(checklistData)
      
      // Enhanced column widths
      const columnWidths = [
        { wch: 8 },  // Row #
        { wch: 12 }, // SC Number
        { wch: 40 }, // Success Criterion
        { wch: 8 },  // Level
        { wch: 20 }, // Principle
        { wch: 30 }, // Guideline
        { wch: 60 }, // Description
        { wch: 15 }, // Status
        { wch: 15 }, // Completion Date
        { wch: 40 }, // Notes
        { wch: 10 }  // Priority
      ]
      worksheet['!cols'] = columnWidths

      // Add header styling
      const headerRange = XLSX.utils.decode_range(worksheet['!ref'] || 'A1')
      for (let C = headerRange.s.c; C <= headerRange.e.c; ++C) {
        const cellAddress = XLSX.utils.encode_cell({ c: C, r: 0 })
        if (!worksheet[cellAddress]) continue
        worksheet[cellAddress].s = {
          font: { bold: true, color: { rgb: "FFFFFF" } },
          fill: { fgColor: { rgb: "1E40AF" } },
          alignment: { horizontal: "center", vertical: "center", wrapText: true }
        }
      }

      // Add autofilter
      const range = XLSX.utils.decode_range(worksheet['!ref'] || 'A1')
      worksheet['!autofilter'] = { ref: XLSX.utils.encode_range(range) }
      
      // Freeze header row
      worksheet['!freeze'] = { xSplit: 0, ySplit: 1, topLeftCell: 'A2', activePane: 'bottomLeft', state: 'frozen' }

      // Create workbook
      const workbook = XLSX.utils.book_new()
      XLSX.utils.book_append_sheet(workbook, worksheet, 'WCAG 2.2 Checklist')
      
      // Create summary sheet
      const summaryData = [
        ['WCAG 2.2 Accessibility Audit Report'],
        ['Generated by Accessibility.build'],
        [''],
        ['AUDIT SUMMARY'],
        ['Total Success Criteria:', stats.total],
        ['Level A Criteria:', stats.byLevel.A],
        ['Level AA Criteria:', stats.byLevel.AA],
        ['Level AAA Criteria:', stats.byLevel.AAA],
        [''],
        ['EXPORT INFORMATION'],
        ['Export Date:', new Date().toLocaleDateString()],
        ['Export Time:', new Date().toLocaleTimeString()],
        [''],
        ['INSTRUCTIONS'],
        ['1. Use the Status column to mark criteria as COMPLETED or NOT COMPLETED'],
        ['2. Add your notes and findings in the Notes column'],
        ['3. Use the Priority column to prioritize Level AA criteria for compliance'],
        ['4. Filter by Level to focus on specific conformance requirements'],
        ['5. Use the Progress Tracking sheet to monitor improvements over time']
      ]
      
      const summarySheet = XLSX.utils.aoa_to_sheet(summaryData)
      summarySheet['!cols'] = [{ wch: 30 }, { wch: 25 }]
      XLSX.utils.book_append_sheet(workbook, summarySheet, 'Audit Summary')

      // Create progress tracking sheet
      const progressData = [
        ['Progress Tracking'],
        [''],
        ['Date', 'Total Completed', 'Level A', 'Level AA', 'Level AAA', 'Notes'],
        [new Date().toLocaleDateString(), 0, 0, 0, 0, 'Initial template']
      ]
      
      const progressSheet = XLSX.utils.aoa_to_sheet(progressData)
      progressSheet['!cols'] = [{ wch: 15 }, { wch: 15 }, { wch: 10 }, { wch: 10 }, { wch: 10 }, { wch: 30 }]
      XLSX.utils.book_append_sheet(workbook, progressSheet, 'Progress Tracking')

      const fileName = `WCAG-2.2-Checklist-Template-${new Date().toISOString().split('T')[0]}.xlsx`
      XLSX.writeFile(workbook, fileName)
    } catch (error) {
      console.error('Error generating Excel:', error)
      alert('Error generating Excel file. Please try again.')
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-white to-emerald-50 dark:from-slate-900 dark:via-slate-800 dark:to-slate-900">
      <div className="container-wide py-16">
        <div className="max-w-4xl mx-auto">
          <div className="mb-8">
            <Link 
              href="/checklists/wcag-2-2"
              className="inline-flex items-center gap-2 text-blue-600 hover:text-blue-700 dark:text-blue-400 dark:hover:text-blue-300 mb-6"
            >
              <ArrowLeft className="w-4 h-4" />
              Back to Interactive Checklist
            </Link>
          </div>

          <Card className="bg-white/95 dark:bg-slate-800/95 backdrop-blur-sm border-2 border-emerald-200 dark:border-emerald-700 shadow-2xl">
            <CardHeader className="text-center pb-4">
              <div className="flex justify-center mb-4">
                <div className="p-4 bg-gradient-to-r from-emerald-600 to-green-700 rounded-2xl">
                  <FileSpreadsheet className="w-12 h-12 text-white" />
                </div>
              </div>
              <CardTitle className="text-4xl font-bold bg-gradient-to-r from-emerald-600 to-green-700 bg-clip-text text-transparent mb-4">
                WCAG 2.2 Checklist Excel Template
              </CardTitle>
              <CardDescription className="text-lg text-slate-600 dark:text-slate-300">
                Download a professional Excel template with all {stats.total} WCAG 2.2 success criteria, ready for your accessibility audit
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="bg-gradient-to-r from-emerald-50 to-green-50 dark:from-emerald-900/20 dark:to-green-900/20 p-6 rounded-xl border border-emerald-200 dark:border-emerald-700">
                <h2 className="text-xl font-semibold text-slate-800 dark:text-slate-200 mb-4">What&apos;s Included:</h2>
                <ul className="space-y-2 text-slate-700 dark:text-slate-300">
                  <li className="flex items-start">
                    <CheckCircle className="w-5 h-5 text-emerald-600 mr-2 mt-0.5 flex-shrink-0" />
                    <span>Complete checklist with all {stats.total} WCAG 2.2 success criteria</span>
                  </li>
                  <li className="flex items-start">
                    <CheckCircle className="w-5 h-5 text-emerald-600 mr-2 mt-0.5 flex-shrink-0" />
                    <span>Pre-formatted columns for Status, Notes, and Completion Date</span>
                  </li>
                  <li className="flex items-start">
                    <CheckCircle className="w-5 h-5 text-emerald-600 mr-2 mt-0.5 flex-shrink-0" />
                    <span>Audit Summary sheet with statistics and instructions</span>
                  </li>
                  <li className="flex items-start">
                    <CheckCircle className="w-5 h-5 text-emerald-600 mr-2 mt-0.5 flex-shrink-0" />
                    <span>Progress Tracking sheet for monitoring improvements</span>
                  </li>
                  <li className="flex items-start">
                    <CheckCircle className="w-5 h-5 text-emerald-600 mr-2 mt-0.5 flex-shrink-0" />
                    <span>Auto-filters and frozen headers for easy navigation</span>
                  </li>
                  <li className="flex items-start">
                    <CheckCircle className="w-5 h-5 text-emerald-600 mr-2 mt-0.5 flex-shrink-0" />
                    <span>Professional styling and conditional formatting</span>
                  </li>
                </ul>
              </div>

              {/* Level Breakdown */}
              <div className="grid grid-cols-3 gap-4">
                <div className="text-center p-4 bg-green-50 dark:bg-green-900/20 rounded-lg border border-green-200 dark:border-green-700">
                  <div className="text-2xl font-bold text-green-600">{stats.byLevel.A}</div>
                  <div className="text-sm text-slate-600 dark:text-slate-400">Level A</div>
                </div>
                <div className="text-center p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg border border-blue-200 dark:border-blue-700">
                  <div className="text-2xl font-bold text-blue-600">{stats.byLevel.AA}</div>
                  <div className="text-sm text-slate-600 dark:text-slate-400">Level AA</div>
                </div>
                <div className="text-center p-4 bg-purple-50 dark:bg-purple-900/20 rounded-lg border border-purple-200 dark:border-purple-700">
                  <div className="text-2xl font-bold text-purple-600">{stats.byLevel.AAA}</div>
                  <div className="text-sm text-slate-600 dark:text-slate-400">Level AAA</div>
                </div>
              </div>

              <div className="flex flex-col sm:flex-row gap-4">
                <Button
                  onClick={downloadExcelTemplate}
                  size="lg"
                  className="flex-1 bg-gradient-to-r from-emerald-600 to-green-700 hover:from-emerald-700 hover:to-green-800 text-white"
                >
                  <Download className="w-5 h-5 mr-2" />
                  Download Excel Template
                </Button>
                <Button
                  asChild
                  variant="outline"
                  size="lg"
                  className="flex-1"
                >
                  <Link href="/checklists/wcag-2-2">
                    Use Interactive Checklist
                  </Link>
                </Button>
              </div>

              <div className="bg-blue-50 dark:bg-blue-900/20 p-4 rounded-lg border border-blue-200 dark:border-blue-700">
                <p className="text-sm text-blue-800 dark:text-blue-300">
                  <strong>Tip:</strong> For real-time progress tracking and interactive features, use our{" "}
                  <Link href="/checklists/wcag-2-2" className="underline font-semibold">Interactive WCAG 2.2 Checklist</Link>{" "}
                  and export your progress when ready.
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}

