export const subprocessors = [
  {
    provider: "Clerk",
    purpose: "Authentication, account management, and session security",
    data: "Account identifiers, name, email, authentication and session data",
    location: "Provider-controlled global infrastructure",
    conditional: "Used for account features",
    policy: "https://clerk.com/legal/privacy",
  },
  {
    provider: "Vercel",
    purpose: "Hosting, content delivery, performance, and aggregate analytics",
    data: "Request, device, network, performance, and deployment data",
    location: "Provider-controlled global infrastructure",
    conditional: "Used across the website",
    policy: "https://vercel.com/legal/privacy-policy",
  },
  {
    provider: "Google Analytics",
    purpose: "Optional website usage analytics",
    data: "Consent-dependent browser, page, event, and approximate location data",
    location: "Provider-controlled global infrastructure",
    conditional: "Loads only after analytics consent",
    policy: "https://policies.google.com/privacy",
  },
  {
    provider: "Stripe",
    purpose: "International payment processing, billing, fraud prevention, and refunds",
    data: "Billing identity, payment and transaction data",
    location: "Provider-controlled global infrastructure",
    conditional: "Used when Stripe is the selected payment provider",
    policy: "https://stripe.com/privacy",
  },
  {
    provider: "Razorpay",
    purpose: "India-region payment processing, billing, fraud prevention, and refunds",
    data: "Billing identity, payment and transaction data",
    location: "India and provider-controlled infrastructure",
    conditional: "Used when Razorpay is the selected payment provider",
    policy: "https://razorpay.com/privacy/",
  },
  {
    provider: "OpenAI",
    purpose: "AI-assisted tool features",
    data: "Feature input such as prompts, images, code, or issue descriptions",
    location: "Provider-controlled global infrastructure",
    conditional: "Used only by features configured for OpenAI",
    policy: "https://openai.com/policies/privacy-policy/",
  },
  {
    provider: "Anthropic and OpenRouter",
    purpose: "Alternative AI-assisted analysis and generation",
    data: "Feature input such as prompts, code, or issue descriptions",
    location: "Provider-controlled global infrastructure",
    conditional: "Used only when the relevant model provider is selected",
    policy: "https://www.anthropic.com/legal/privacy",
  },
  {
    provider: "Sanity",
    purpose: "Content management and blog delivery",
    data: "Published editorial content and content-management account data",
    location: "Provider-controlled global infrastructure",
    conditional: "Used for published content",
    policy: "https://www.sanity.io/legal/privacy",
  },
  {
    provider: "Formspree and Resend",
    purpose: "Contact-form delivery and requested or transactional email",
    data: "Name, email, message, organization, and email delivery metadata",
    location: "Provider-controlled global infrastructure",
    conditional: "Used when a form or email workflow is requested",
    policy: "https://formspree.io/legal/privacy-policy/",
  },
] as const
