import { FAMILY_NAMES, STOPS } from "../scales"
import type { SemanticTokens } from "../tokens"
import { type ExportFile, type ExportInput, kebab, prefixed } from "./types"

function scaleVars(scales: ExportInput["scales"], prefix?: string): string {
  const lines: string[] = []
  for (const family of FAMILY_NAMES) {
    for (const stop of STOPS) {
      lines.push(`  --${prefixed(prefix, `color-${family}-${stop}`)}: ${scales[family][stop]};`)
    }
    lines.push("")
  }
  return lines.join("\n").trimEnd()
}

const SEMANTIC_KEYS: ReadonlyArray<keyof SemanticTokens> = [
  "background",
  "surface",
  "raised",
  "foreground",
  "muted",
  "subtle",
  "border",
  "borderStrong",
  "primary",
  "primaryHover",
  "primaryActive",
  "primaryForeground",
  "primarySurface",
  "secondary",
  "secondaryHover",
  "secondaryForeground",
  "secondarySurface",
  "accent",
  "accentHover",
  "accentForeground",
  "accentSurface",
  "success",
  "successForeground",
  "successSurface",
  "warning",
  "warningForeground",
  "warningSurface",
  "danger",
  "dangerForeground",
  "dangerSurface",
  "info",
  "infoForeground",
  "infoSurface",
  "focus",
  "focusRing",
  "disabled",
  "disabledForeground",
]

function tokenName(key: string): string {
  // primaryHover → primary-hover
  return key.replace(/([A-Z])/g, "-$1").toLowerCase()
}

function semanticVars(t: SemanticTokens, prefix?: string): string {
  const lines = SEMANTIC_KEYS.map((key) => {
    const value = t[key] as string
    return `  --${prefixed(prefix, tokenName(key))}: ${value};`
  })
  // Chart colors as numbered tokens
  t.chartColors.forEach((c, i) => {
    lines.push(`  --${prefixed(prefix, `chart-${i + 1}`)}: ${c};`)
  })
  return lines.join("\n")
}

export function exportCSS(input: ExportInput): ExportFile {
  const { name, scales, tokens, prefix } = input
  const slug = kebab(name)
  const content = `/* ${name} — generated by Accessible Palette Studio */

:root {
${scaleVars(scales, prefix)}

${semanticVars(tokens.light, prefix)}
}

[data-theme="dark"] {
${semanticVars(tokens.dark, prefix)}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${semanticVars(tokens.dark, prefix).replace(/^/gm, "  ")}
  }
}
`
  return { filename: `${slug}.css`, language: "css", content }
}
