import { FAMILY_NAMES, STOPS } from "../scales"
import type { SemanticTokens } from "../tokens"
import { type ExportFile, type ExportInput, kebab } from "./types"

/**
 * W3C Design Tokens Community Group format.
 * Works with Style Dictionary, Tokens Studio, and Specify.
 * Spec: https://tr.designtokens.org/format/
 */
export function exportDTCG(input: ExportInput): ExportFile {
  const { name, scales, tokens } = input
  const slug = kebab(name)

  const color: Record<string, unknown> = {}
  for (const family of FAMILY_NAMES) {
    const scaleObj: Record<string, unknown> = {}
    for (const stop of STOPS) {
      scaleObj[String(stop)] = { $value: scales[family][stop], $type: "color" }
    }
    color[family] = scaleObj
  }

  const semantic = {
    light: semanticGroup(tokens.light),
    dark: semanticGroup(tokens.dark),
  }

  const doc = {
    $schema: "https://schemas.designtokens.org/draft/2024-01/tokens.schema.json",
    $description: `${name} — generated by Accessible Palette Studio`,
    color,
    semantic,
  }

  return {
    filename: `${slug}.tokens.json`,
    language: "json",
    content: JSON.stringify(doc, null, 2) + "\n",
  }
}

function semanticGroup(t: SemanticTokens): Record<string, unknown> {
  const keys = Object.keys(t).filter(
    (k) => k !== "mode" && k !== "chartColors"
  ) as (keyof SemanticTokens)[]
  const out: Record<string, unknown> = {}
  for (const k of keys) {
    const value = t[k]
    if (typeof value === "string") {
      out[kebabKey(k)] = { $value: value, $type: "color" }
    }
  }
  const chart: Record<string, unknown> = {}
  t.chartColors.forEach((c, i) => {
    chart[String(i + 1)] = { $value: c, $type: "color" }
  })
  out.chart = chart
  return out
}

function kebabKey(s: string): string {
  return s.replace(/([A-Z])/g, "-$1").toLowerCase()
}
