import { FAMILY_NAMES, STOPS } from "../scales"
import type { SemanticTokens } from "../tokens"
import { type ExportFile, type ExportInput, kebab } from "./types"

function camel(name: string): string {
  return name
    .replace(/[-_]+(\w)/g, (_, c: string) => c.toUpperCase())
    .replace(/^[A-Z]/, (c) => c.toLowerCase())
}

function pascal(name: string): string {
  const c = camel(name)
  return c.charAt(0).toUpperCase() + c.slice(1)
}

function composeColor(hex: string): string {
  const h = hex.replace("#", "").toUpperCase()
  const padded = h.length === 6 ? `FF${h}` : h
  return `Color(0x${padded})`
}

/**
 * Kotlin — Jetpack Compose Color object with full scale + light/dark semantic objects.
 */
export function exportKotlin(input: ExportInput): ExportFile {
  const { name, scales, tokens } = input
  const slug = kebab(name)
  const namespace = pascal(slug)

  const scaleLines: string[] = []
  for (const family of FAMILY_NAMES) {
    for (const stop of STOPS) {
      scaleLines.push(
        `    val ${family}${stop} = ${composeColor(scales[family][stop])}`
      )
    }
  }

  const semanticLines = (t: SemanticTokens) => {
    const keys = Object.keys(t).filter(
      (k) => k !== "mode" && k !== "chartColors"
    ) as (keyof SemanticTokens)[]
    const lines: string[] = []
    for (const k of keys) {
      const value = t[k]
      if (typeof value === "string") {
        lines.push(`        val ${camel(k)} = ${composeColor(value)}`)
      }
    }
    return lines.join("\n")
  }

  const content = `// ${name} — generated by Accessible Palette Studio
package com.example.theme

import androidx.compose.ui.graphics.Color

object ${namespace} {
${scaleLines.join("\n")}

    object Light {
${semanticLines(tokens.light)}
    }

    object Dark {
${semanticLines(tokens.dark)}
    }
}
`
  return { filename: `${namespace}.kt`, language: "kotlin", content }
}
