import { hexToRgb } from "../oklch"
import { FAMILY_NAMES, STOPS } from "../scales"
import type { SemanticTokens } from "../tokens"
import { type ExportFile, type ExportInput, kebab } from "./types"

function camel(name: string): string {
  return name
    .replace(/[-_]+(\w)/g, (_, c: string) => c.toUpperCase())
    .replace(/^[A-Z]/, (c) => c.toLowerCase())
}

function pascal(name: string): string {
  const c = camel(name)
  return c.charAt(0).toUpperCase() + c.slice(1)
}

function uiColorLiteral(hex: string): string {
  const { r, g, b } = hexToRgb(hex)
  return `UIColor(red: ${r.toFixed(3)}, green: ${g.toFixed(3)}, blue: ${b.toFixed(3)}, alpha: 1.0)`
}

/**
 * Swift — UIColor extension with the full scale + a semantic enum.
 * Drop into an iOS project; works with SwiftUI via `Color(uiColor: AppColor.primary500)`.
 */
export function exportSwift(input: ExportInput): ExportFile {
  const { name, scales, tokens } = input
  const slug = kebab(name)
  const namespace = pascal(slug)

  const scaleLines: string[] = []
  for (const family of FAMILY_NAMES) {
    for (const stop of STOPS) {
      scaleLines.push(`    static let ${family}${stop} = ${uiColorLiteral(scales[family][stop])}`)
    }
  }

  const semanticLines = (mode: "light" | "dark", t: SemanticTokens) => {
    const keys = Object.keys(t).filter(
      (k) => k !== "mode" && k !== "chartColors"
    ) as (keyof SemanticTokens)[]
    const lines: string[] = []
    for (const k of keys) {
      const value = t[k]
      if (typeof value === "string") {
        lines.push(`        static let ${camel(k)} = ${uiColorLiteral(value)}`)
      }
    }
    return lines.join("\n")
  }

  const content = `// ${name} — generated by Accessible Palette Studio
import UIKit

enum ${namespace} {
${scaleLines.join("\n")}

    enum Light {
${semanticLines("light", tokens.light)}
    }

    enum Dark {
${semanticLines("dark", tokens.dark)}
    }
}
`
  return { filename: `${namespace}.swift`, language: "swift", content }
}
