import type { Metadata } from "next"
import Link from "next/link"
import WCAGSEOEnhancements from "@/components/wcag/seo-enhancements"
import WCAGBreadcrumb from "@/components/wcag/breadcrumb"
import { FAQStructuredData } from "@/components/seo/structured-data"
import { CriterionLinks } from "@/components/wcag/criterion-links"

export const metadata: Metadata = {
  title: "WCAG 2.2.3 No Timing — Remove Time Limits Entirely",
  description:
    "WCAG 2.2.3 No Timing explained: timing must not be essential to any activity, except real-time events and synchronized media. Examples, exceptions, and testing.",
  keywords: [
    "WCAG 2.2.3",
    "No Timing",
    "time limits accessibility",
    "remove time limits",
    "untimed activity",
    "real-time event exception",
    "Level AAA",
    "WCAG 2.2",
    "enough time",
  ],
  alternates: {
    canonical: "/wcag/2-2-3",
  },
  openGraph: {
    title: "WCAG 2.2.3 No Timing — Remove Time Limits Entirely",
    description:
      "The AAA standard for time limits: timing must not be an essential part of any event or activity, except non-interactive synchronized media and real-time events.",
    url: "/wcag/2-2-3",
    type: "article",
    siteName: "Accessibility.build",
    images: [
      {
        url: "/api/og?title=WCAG%202.2.3%20No%20Timing&section=WCAG",
        width: 1200,
        height: 630,
        alt: "WCAG 2.2.3 No Timing guide",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "WCAG 2.2.3 No Timing — Remove Time Limits Entirely",
    description:
      "Timing must not be essential to any event or activity. The two exceptions, how 2.2.3 differs from 2.2.1, and how to test it.",
    images: [
      {
        url: "/api/og?title=WCAG%202.2.3%20No%20Timing&section=WCAG",
        width: 1200,
        height: 630,
      },
    ],
  },
}

const faqs = [
  {
    question: "What does WCAG 2.2.3 No Timing require?",
    answer:
      "It requires that timing is not an essential part of the event or activity presented by the content, except for non-interactive synchronized media and real-time events. In plain terms: at Level AAA, users should be able to take as long as they need for anything the content asks of them. Where 2.2.1 Timing Adjustable (Level A) lets you keep time limits as long as users can turn them off, adjust them, or extend them, 2.2.3 says the activity itself should not depend on time at all.",
  },
  {
    question: "How is 2.2.3 different from 2.2.1 Timing Adjustable?",
    answer:
      "2.2.1 (Level A) accepts that time limits exist and regulates them: the user must be able to turn off, adjust to at least ten times the default, or repeatedly extend each limit, with several exceptions including 'essential' limits. 2.2.3 (Level AAA) goes further: it removes the premise. Timing must not be essential to the activity in the first place, and there is no 'essential exception' — only non-interactive synchronized media and real-time events are exempt. A timed certification exam can pass 2.2.1 under its essential exception, but it fails 2.2.3.",
  },
  {
    question: "What counts as a 'real-time event' under the exception?",
    answer:
      "A real-time event is one that occurs at the same time as viewing and is not generated by the content itself — an online auction that genuinely closes at a fixed moment, a live webcast, a ticket sale for a physical event, or a multiplayer game synchronized among live participants. The timing there comes from the real world, not from a design decision, so the content cannot remove it. A countdown you invented to create urgency is not a real-time event.",
  },
  {
    question: "Why is non-interactive synchronized media exempt?",
    answer:
      "A movie or a narrated animation is inherently temporal — video frames and audio are synchronized on a timeline, and 'removing timing' from them is meaningless. The exemption covers only the non-interactive kind: content the user watches rather than operates. If media becomes interactive — say, a training video that pauses and demands an answer within 15 seconds — that interaction is an activity, and its time limit is subject to the criterion.",
  },
  {
    question: "Does 2.2.3 forbid session timeouts for security?",
    answer:
      "Not exactly. Session timeouts driven by security policy are about the session, not about making timing part of the activity. The W3C's guidance treats untimed activities as compatible with sessions that expire, provided the user does not lose data or progress — which is exactly what 2.2.5 Re-authenticating (AAA) and 2.2.6 Timeouts (AAA) govern. The clean AAA combination is: no task is time-pressured (2.2.3), users are warned about inactivity limits (2.2.6), and re-authenticating never loses their work (2.2.5).",
  },
  {
    question: "Who benefits from removing time limits entirely?",
    answer:
      "Anyone who needs more time than a designer guessed: people using screen readers who navigate content linearly, people with motor disabilities using switch access or on-screen keyboards, people with cognitive or learning disabilities who read and process more slowly, people with anxiety for whom countdowns degrade performance, and users of magnification who see a small window of the page at a time. Time pressure multiplies the difficulty of every other barrier — removing it is one of the most powerful accessibility improvements available.",
  },
]

export default function WCAG223Page() {
  return (
    <>
      <WCAGSEOEnhancements
        title="WCAG 2.2.3: No Timing"
        description="Timing is not an essential part of the event or activity presented by the content, except for non-interactive synchronized media and real-time events."
        criteria="2.2.3"
        level="AAA"
        principle="Operable"
        guideline="2.2 Enough Time"
        url="https://accessibility.build/wcag/2-2-3"
        category="Enough Time"
        relatedCriteria={["2.2.1", "2.2.5", "2.2.6"]}
      />
      <FAQStructuredData faqs={faqs} />

      <div className="min-h-screen pt-12 bg-white dark:bg-slate-950">
        <article className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
          <WCAGBreadcrumb items={[]} current="2.2.3 No Timing" />

          {/* Header */}
          <header className="mb-12">
            <div className="flex flex-wrap items-center gap-2 mb-4">
              <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-semibold bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300">
                Level AAA
              </span>
              <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-semibold bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300">
                Principle 2: Operable
              </span>
              <span className="inline-flex items-center px-3 py-1 rounded-full text-sm font-semibold bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300">
                Guideline 2.2 Enough Time
              </span>
            </div>
            <h1 className="text-4xl sm:text-5xl font-bold text-slate-900 dark:text-white mb-5 tracking-tight">
              WCAG 2.2.3: No Timing
            </h1>
            <p className="text-xl text-slate-600 dark:text-slate-300 leading-relaxed">
              Level A says time limits must be adjustable. Level AAA asks a sharper
              question:{" "}
              <strong className="text-slate-900 dark:text-white">
                why is there a clock at all?
              </strong>{" "}
              Under 2.2.3, timing must not be an essential part of any event or
              activity your content presents — users get as long as they need, whether
              that is thirty seconds or three days. Only two things escape: media that
              is inherently temporal, and events happening in real time.
            </p>
          </header>

          {/* Official text */}
          <section
            aria-labelledby="official-text"
            className="mb-12 rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/40 p-6"
          >
            <h2
              id="official-text"
              className="text-sm font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400 mb-3"
            >
              The success criterion, in full
            </h2>
            <blockquote className="text-slate-700 dark:text-slate-300 leading-relaxed border-l-4 border-purple-500 pl-4">
              Timing is not an essential part of the event or activity presented by
              the content, except for non-interactive synchronized media and
              real-time events.
            </blockquote>
            <p className="text-slate-600 dark:text-slate-300 leading-relaxed mt-4 text-sm">
              Notice what is missing compared with{" "}
              <Link href="/wcag/2-2-1" className="text-blue-600 dark:text-blue-400 hover:underline">
                2.2.1 Timing Adjustable
              </Link>
              : there is no &ldquo;essential exception&rdquo; you can invoke for your
              own design. If the timing is not imposed by a real-world event or the
              nature of synchronized media, it must go.
            </p>
          </section>

          {/* On this page */}
          <nav
            aria-label="On this page"
            className="mb-12 rounded-xl border border-slate-200 dark:border-slate-800 p-6"
          >
            <h2 className="text-lg font-semibold text-slate-900 dark:text-white mb-3">
              On this page
            </h2>
            <ul className="grid sm:grid-cols-2 gap-2 text-blue-600 dark:text-blue-400">
              <li><a className="hover:underline" href="#who">Who this helps</a></li>
              <li><a className="hover:underline" href="#exceptions">The two exceptions</a></li>
              <li><a className="hover:underline" href="#ladder">The 2.2.x ladder: A to AAA</a></li>
              <li><a className="hover:underline" href="#examples">Pass and fail examples</a></li>
              <li><a className="hover:underline" href="#mistakes">Common failures</a></li>
              <li><a className="hover:underline" href="#testing">How to test</a></li>
              <li><a className="hover:underline" href="#faq">FAQ</a></li>
            </ul>
          </nav>

          {/* Who */}
          <section aria-labelledby="who" className="mb-12">
            <h2 id="who" className="text-3xl font-bold text-slate-900 dark:text-white mb-4">
              Who this helps
            </h2>
            <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
              Every interaction on the web takes different people wildly different
              amounts of time. A form that takes one user ninety seconds can take
              another user forty-five minutes — same form, same intent, different
              body and tools:
            </p>
            <div className="grid sm:grid-cols-2 gap-4 mb-4">
              {[
                {
                  t: "Screen reader users",
                  d: "Content is consumed linearly, one element at a time. Skimming a page under time pressure is not an option.",
                },
                {
                  t: "People with motor disabilities",
                  d: "Switch access, eye gaze, and on-screen keyboards make each input action slower — sometimes by an order of magnitude.",
                },
                {
                  t: "People with cognitive disabilities",
                  d: "Reading, comprehension, and decision-making can take longer; a ticking clock also actively worsens performance through stress.",
                },
                {
                  t: "People who are deaf or hard of hearing",
                  d: "Users whose first language is a sign language may read written language more slowly — timed reading tasks penalize them directly.",
                },
              ].map((item) => (
                <div key={item.t} className="rounded-xl border border-slate-200 dark:border-slate-800 p-5">
                  <h3 className="font-semibold text-slate-900 dark:text-white mb-1">{item.t}</h3>
                  <p className="text-slate-600 dark:text-slate-300 text-sm leading-relaxed">{item.d}</p>
                </div>
              ))}
            </div>
            <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
              Adjustable limits (2.2.1) help, but they still put the burden on the
              user to notice the warning and act on it. Removing timing entirely
              removes the burden.
            </p>
          </section>

          {/* Exceptions */}
          <section aria-labelledby="exceptions" className="mb-12">
            <h2 id="exceptions" className="text-3xl font-bold text-slate-900 dark:text-white mb-4">
              The two exceptions
            </h2>
            <div className="space-y-4 mb-4">
              <div className="rounded-xl border border-slate-200 dark:border-slate-800 p-5">
                <h3 className="font-semibold text-slate-900 dark:text-white mb-1">
                  1. Non-interactive synchronized media
                </h3>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed text-sm">
                  A film, a narrated animation, a recorded lecture — audio and video
                  synchronized on a timeline. Timing is the medium; it cannot be
                  removed. The moment the media demands interaction on a deadline
                  (&ldquo;answer within 15 seconds or the video restarts&rdquo;), that
                  interaction is an activity again and the exception no longer covers
                  it.
                </p>
              </div>
              <div className="rounded-xl border border-slate-200 dark:border-slate-800 p-5">
                <h3 className="font-semibold text-slate-900 dark:text-white mb-1">
                  2. Real-time events
                </h3>
                <p className="text-slate-600 dark:text-slate-300 leading-relaxed text-sm">
                  Events that happen at the same time as viewing and are not created
                  by the content: a live auction closing, a webcast, competitive
                  multiplayer play among live opponents, tickets for a show that
                  starts at 8 p.m. The world sets the clock, not the designer. A
                  marketing countdown (&ldquo;offer ends in 09:59!&rdquo;) that you
                  control does not qualify — although note that a purely decorative
                  urgency timer that gates nothing is not making timing{" "}
                  <em>essential</em> either.
                </p>
              </div>
            </div>
            <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
              The test for both is the same: does the timing originate outside the
              content&rsquo;s control, or is it a design choice? Design choices must
              be removed at AAA.
            </p>
          </section>

          {/* Ladder */}
          <section aria-labelledby="ladder" className="mb-12">
            <h2 id="ladder" className="text-3xl font-bold text-slate-900 dark:text-white mb-4">
              The 2.2.x ladder: from adjustable to absent
            </h2>
            <p className="text-slate-600 dark:text-slate-300 leading-relaxed mb-4">
              Guideline 2.2 Enough Time escalates through the conformance levels.
              Understanding where 2.2.3 sits makes it easy to apply:
            </p>
            <ul className="space-y-3 mb-4">
              {[
                {
                  n: "2.2.1 Timing Adjustable (A)",
                  href: "/wcag/2-2-1",
                  d: "Time limits may exist, but users must be able to turn them off, adjust them to at least 10× the default, or extend them — with exceptions for real-time events, essential limits, and limits over 20 hours.",
                },
                {
                  n: "2.2.3 No Timing (AAA)",
                  href: null,
                  d: "This criterion. Timing must not be essential to the activity at all. The 'essential' escape hatch of 2.2.1 disappears; only synchronized media and real-time events remain exempt.",
                },
                {
                  n: "2.2.5 Re-authenticating (AAA)",
                  href: "/wcag/2-2-5",
                  d: "When a secure session does expire, users can continue where they left off — with all data intact — after logging back in.",
                },
                {
                  n: "2.2.6 Timeouts (AAA)",
                  href: "/wcag/2-2-6",
                  d: "If inactivity can cause data loss, users are told the duration up front (unless data is kept for more than 20 hours).",
                },
              ].map((item) => (
                <li key={item.n} className="flex gap-3 rounded-lg border border-slate-200 dark:border-slate-800 p-4">
                  <span aria-hidden="true" className="text-purple-500 font-bold">→</span>
                  <span className="text-slate-700 dark:text-slate-300 leading-relaxed">
                    {item.href ? (
                      <Link href={item.href} className="text-blue-600 dark:text-blue-400 hover:underline font-medium">
                        {item.n}
                      </Link>
                    ) : (
                      <strong className="text-slate-900 dark:text-white">{item.n}</strong>
                    )}{" "}
                    — {item.d}
                  </span>
                </li>
              ))}
            </ul>
            <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
              A practical way to design for the whole ladder at once: build every task
              so it can be paused indefinitely and resumed without loss. Auto-save
              plus no deadlines satisfies 2.2.3 directly and makes 2.2.5 and 2.2.6
              almost free.
            </p>
          </section>

          {/* Examples */}
          <section aria-labelledby="examples" className="mb-12">
            <h2 id="examples" className="text-3xl font-bold text-slate-900 dark:text-white mb-4">
              Pass and fail examples
            </h2>
            <div className="grid sm:grid-cols-2 gap-4">
              <div className="rounded-xl border border-emerald-200 dark:border-emerald-900/40 bg-emerald-50 dark:bg-emerald-950/20 p-5">
                <h3 className="font-semibold text-emerald-800 dark:text-emerald-300 mb-2">
                  ✓ Passes 2.2.3
                </h3>
                <ul className="space-y-2 text-sm text-slate-700 dark:text-slate-300 leading-relaxed list-disc pl-4">
                  <li>A checkout that holds the cart indefinitely and auto-saves the address form as the user types.</li>
                  <li>An online quiz with no time limit — completion is judged on answers, not speed.</li>
                  <li>A word game that offers an untimed mode alongside its timed &ldquo;challenge&rdquo; mode.</li>
                  <li>A live auction page — real-time event exception — that clearly shows the auction close time.</li>
                  <li>A training video (non-interactive synchronized media) with pause, and untimed knowledge checks afterwards.</li>
                </ul>
              </div>
              <div className="rounded-xl border border-rose-200 dark:border-rose-900/40 bg-rose-50 dark:bg-rose-950/20 p-5">
                <h3 className="font-semibold text-rose-800 dark:text-rose-300 mb-2">
                  ✗ Fails 2.2.3
                </h3>
                <ul className="space-y-2 text-sm text-slate-700 dark:text-slate-300 leading-relaxed list-disc pl-4">
                  <li>A ticket checkout that releases your seats after 8 minutes when no genuine scarcity forces it.</li>
                  <li>A timed certification exam — its &ldquo;essential&rdquo; time limit can pass 2.2.1 but fails 2.2.3.</li>
                  <li>A form that discards everything after 15 minutes of inactivity with no way to recover it.</li>
                  <li>A CAPTCHA or verification code that expires so fast that slower users must restart repeatedly.</li>
                  <li>An e-learning module where each question must be answered within 30 seconds by design.</li>
                </ul>
              </div>
            </div>
          </section>

          {/* Common failures */}
          <section aria-labelledby="mistakes" className="mb-12">
            <h2 id="mistakes" className="text-3xl font-bold text-slate-900 dark:text-white mb-4">
              Common failures
            </h2>
            <ul className="space-y-3">
              {[
                "Manufactured urgency: countdowns that gate a purchase or price purely as a conversion tactic, making timing essential where nothing real requires it.",
                "Session-expiry designs where the timer effectively becomes part of the task — the user must finish before an arbitrary clock runs out or lose all progress.",
                "Timed tests and quizzes where speed is not the skill being measured, penalizing users who need assistive technology or more processing time.",
                "One-time codes and CAPTCHAs with expiry windows too short for users of screen readers or switch access to complete entry.",
                "Interactive media that pauses and demands a response within a deadline, assuming the media exception covers it — it does not, because the interaction is an activity.",
                "Auto-advancing multi-step wizards that move on after a fixed delay whether or not the user has finished the current step.",
                "Claiming the real-time exception for a timer the site itself created, like a self-imposed 'flash sale' clock that could simply be removed.",
              ].map((m) => (
                <li key={m} className="flex gap-3 rounded-lg border border-rose-200 dark:border-rose-900/40 bg-rose-50 dark:bg-rose-950/20 p-4">
                  <span aria-hidden="true" className="text-rose-500 font-bold">✗</span>
                  <span className="text-slate-700 dark:text-slate-300 leading-relaxed">{m}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* Testing */}
          <section aria-labelledby="testing" className="mb-12">
            <h2 id="testing" className="text-3xl font-bold text-slate-900 dark:text-white mb-4">
              How to test for 2.2.3
            </h2>
            <ol className="space-y-4">
              {[
                {
                  t: "Inventory every clock",
                  d: "List everything time-driven on the page or in the flow: session timers, countdowns, expiring codes, auto-advancing steps, timed questions, carousels that gate content, games. Include timers that are invisible until they fire.",
                },
                {
                  t: "Classify each against the two exceptions",
                  d: "For each timer ask: is this a real-time event whose clock the content does not control, or non-interactive synchronized media? If neither, timing must not be essential to the activity.",
                },
                {
                  t: "Walk away mid-task",
                  d: "Start each key task, then stop interacting — for ten minutes, an hour, longer if feasible. Return and continue. If the task failed, reset, expired, or lost data, timing was essential and the criterion fails.",
                },
                {
                  t: "Complete tasks at assistive-technology speed",
                  d: "Run the flow with a screen reader or keyboard-only, deliberately slowly. Any point where slowness alone causes failure — an expired code, a released reservation, a skipped question — is a defect.",
                },
                {
                  t: "Check timed modes have untimed equivalents",
                  d: "Where time pressure is part of the fun or the pedagogy, verify an untimed mode offers the same content and completion credit. An untimed alternative that covers the same functionality satisfies the requirement for that activity.",
                },
              ].map((step, i) => (
                <li key={step.t} className="flex gap-4 rounded-xl border border-slate-200 dark:border-slate-800 p-5">
                  <span className="flex-shrink-0 w-8 h-8 rounded-full bg-purple-600 text-white font-bold flex items-center justify-center">
                    {i + 1}
                  </span>
                  <div>
                    <h3 className="font-semibold text-slate-900 dark:text-white mb-1">{step.t}</h3>
                    <p className="text-slate-600 dark:text-slate-300 leading-relaxed">{step.d}</p>
                  </div>
                </li>
              ))}
            </ol>
            <p className="text-slate-600 dark:text-slate-300 leading-relaxed mt-5">
              No automated tool can find these failures — timers usually live in
              application logic, not markup. Pair this review with the full{" "}
              <Link href="/checklists/wcag-2-2" className="text-blue-600 dark:text-blue-400 hover:underline font-medium">
                WCAG 2.2 checklist
              </Link>
              .
            </p>
          </section>

          {/* FAQ */}
          <section aria-labelledby="faq" className="mb-4">
            <h2 id="faq" className="text-3xl font-bold text-slate-900 dark:text-white mb-6">
              Frequently asked questions
            </h2>
            <div className="space-y-4">
              {faqs.map((f) => (
                <details
                  key={f.question}
                  className="group rounded-xl border border-slate-200 dark:border-slate-800 p-5 [&_summary]:cursor-pointer"
                >
                  <summary className="font-semibold text-slate-900 dark:text-white list-none flex items-center justify-between gap-4">
                    {f.question}
                    <span aria-hidden="true" className="text-slate-400 group-open:rotate-180 transition-transform">
                      ▾
                    </span>
                  </summary>
                  <p className="mt-3 text-slate-600 dark:text-slate-300 leading-relaxed">{f.answer}</p>
                </details>
              ))}
            </div>
          </section>

          <CriterionLinks number="2.2.3" />
        </article>
      </div>
    </>
  )
}
