"use client"

import { useState, useMemo, useCallback } from "react"
import { FileText, FileSpreadsheet, CheckSquare } from "lucide-react"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"

interface ChecklistItem {
  id: string
  label: string
  description?: string
  category?: string
}

interface DownloadableChecklistProps {
  title: string
  items: ChecklistItem[]
  className?: string
}

export function DownloadableChecklist({
  title,
  items,
  className,
}: DownloadableChecklistProps) {
  const [checkedItems, setCheckedItems] = useState<Set<string>>(new Set())
  const [isExporting, setIsExporting] = useState(false)

  const toggleItem = useCallback((id: string) => {
    setCheckedItems((prev) => {
      const next = new Set(prev)
      if (next.has(id)) {
        next.delete(id)
      } else {
        next.add(id)
      }
      return next
    })
  }, [])

  // Group items by category
  const groupedItems = useMemo(() => {
    const groups: Record<string, ChecklistItem[]> = {}
    const uncategorized: ChecklistItem[] = []

    items.forEach((item) => {
      if (item.category) {
        if (!groups[item.category]) {
          groups[item.category] = []
        }
        groups[item.category].push(item)
      } else {
        uncategorized.push(item)
      }
    })

    return { groups, uncategorized }
  }, [items])

  const hasCategories = Object.keys(groupedItems.groups).length > 0

  const exportToPDF = useCallback(async () => {
    setIsExporting(true)
    try {
      const [jsPDFModule, { default: autoTable }] = await Promise.all([
        import("jspdf"),
        import("jspdf-autotable"),
      ])

      const doc = new jsPDFModule.jsPDF("p", "mm", "a4")

      // Title
      doc.setFontSize(18)
      doc.setFont("helvetica", "bold")
      doc.text(title, 20, 25)

      doc.setFontSize(10)
      doc.setFont("helvetica", "normal")
      doc.text(
        `Generated on ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
        20,
        33
      )
      doc.text(`${checkedItems.size} of ${items.length} items completed`, 20, 39)

      // Build table data
      const tableHeaders = ["Item", "Description", "Category", "Status"]
      const tableData = items.map((item) => [
        item.label,
        item.description || "",
        item.category || "",
        checkedItems.has(item.id) ? "Done" : "Pending",
      ])

      autoTable(doc, {
        head: [tableHeaders],
        body: tableData,
        startY: 48,
        styles: {
          fontSize: 9,
          cellPadding: 3,
          overflow: "linebreak",
          halign: "left",
        },
        headStyles: {
          fillColor: [59, 130, 246],
          textColor: [255, 255, 255],
          fontStyle: "bold",
          fontSize: 10,
        },
        columnStyles: {
          0: { cellWidth: 55 },
          1: { cellWidth: 65 },
          2: { cellWidth: 35 },
          3: { cellWidth: 20, halign: "center" },
        },
        alternateRowStyles: {
          fillColor: [248, 250, 252],
        },
        didParseCell: function (data) {
          if (data.column.index === 3 && data.section === "body") {
            if (data.cell.raw === "Done") {
              data.cell.styles.textColor = [22, 163, 74]
              data.cell.styles.fontStyle = "bold"
            } else {
              data.cell.styles.textColor = [156, 163, 175]
            }
          }
        },
      })

      // Footer
      const pageHeight = doc.internal.pageSize.height
      doc.setFontSize(8)
      doc.setFont("helvetica", "normal")
      doc.setTextColor(150, 150, 150)
      doc.text("Generated by Accessibility.build", 20, pageHeight - 10)

      const fileName = `${title.replace(/[^a-zA-Z0-9]+/g, "-").toLowerCase()}-checklist-${new Date().toISOString().split("T")[0]}.pdf`
      doc.save(fileName)
    } catch (error) {
      console.error("Error exporting to PDF:", error)
    } finally {
      setIsExporting(false)
    }
  }, [title, items, checkedItems])

  const exportToExcel = useCallback(async () => {
    setIsExporting(true)
    try {
      const XLSX = await import("xlsx")

      const workbook = XLSX.utils.book_new()

      // Build checklist data
      const headers = ["Item", "Description", "Category", "Status"]
      const rows = items.map((item) => [
        item.label,
        item.description || "",
        item.category || "",
        checkedItems.has(item.id) ? "Done" : "Pending",
      ])

      const wsData = [headers, ...rows]
      const worksheet = XLSX.utils.aoa_to_sheet(wsData)

      // Column widths
      worksheet["!cols"] = [
        { wch: 45 },
        { wch: 55 },
        { wch: 25 },
        { wch: 12 },
      ]

      // Add autofilter for easy sorting/filtering in Excel
      const range = XLSX.utils.decode_range(worksheet["!ref"] || "A1")
      worksheet["!autofilter"] = { ref: XLSX.utils.encode_range(range) }

      XLSX.utils.book_append_sheet(workbook, worksheet, "Checklist")

      const fileName = `${title.replace(/[^a-zA-Z0-9]+/g, "-").toLowerCase()}-checklist-${new Date().toISOString().split("T")[0]}.xlsx`
      XLSX.writeFile(workbook, fileName)
    } catch (error) {
      console.error("Error exporting to Excel:", error)
    } finally {
      setIsExporting(false)
    }
  }, [title, items, checkedItems])

  const renderChecklistItem = (item: ChecklistItem) => {
    const isChecked = checkedItems.has(item.id)
    return (
      <div
        key={item.id}
        className={cn(
          "flex items-start gap-3 p-3 rounded-lg transition-all duration-200",
          isChecked
            ? "bg-emerald-50/50 dark:bg-emerald-950/20"
            : "hover:bg-slate-50 dark:hover:bg-slate-800/50"
        )}
      >
        <Checkbox
          id={`checklist-${item.id}`}
          checked={isChecked}
          onCheckedChange={() => toggleItem(item.id)}
          className="mt-0.5 border-slate-400 dark:border-slate-500 data-[state=checked]:bg-emerald-500 data-[state=checked]:border-emerald-500"
        />
        <label
          htmlFor={`checklist-${item.id}`}
          className="flex-1 cursor-pointer select-none"
        >
          <span
            className={cn(
              "text-sm font-medium leading-snug transition-colors",
              isChecked
                ? "text-slate-500 dark:text-slate-400 line-through"
                : "text-slate-800 dark:text-slate-200"
            )}
          >
            {item.label}
          </span>
          {item.description && (
            <p
              className={cn(
                "text-xs mt-1 leading-relaxed",
                isChecked
                  ? "text-slate-400 dark:text-slate-500"
                  : "text-slate-600 dark:text-slate-400"
              )}
            >
              {item.description}
            </p>
          )}
        </label>
      </div>
    )
  }

  return (
    <div
      className={cn(
        "rounded-lg border border-slate-200 dark:border-slate-700 overflow-hidden bg-white dark:bg-slate-900 shadow-sm",
        className
      )}
    >
      {/* Download bar */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3 px-5 py-3.5 bg-gradient-to-r from-slate-50 to-slate-100 dark:from-slate-800/50 dark:to-slate-800/80 border-b border-slate-200 dark:border-slate-700">
        <div className="flex items-center gap-3">
          <div className="p-1.5 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-lg shadow-sm">
            <CheckSquare className="w-4 h-4 text-white" />
          </div>
          <div>
            <h3 className="font-bold text-slate-900 dark:text-white text-sm sm:text-base">
              {title}
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              {checkedItems.size} of {items.length} completed
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={exportToPDF}
            disabled={isExporting}
            className="h-8 px-3 text-xs gap-1.5 bg-white dark:bg-slate-800 border-slate-300 dark:border-slate-600 hover:bg-blue-50 dark:hover:bg-blue-900/30 hover:border-blue-400 dark:hover:border-blue-500 hover:text-blue-700 dark:hover:text-blue-300 transition-all"
          >
            <FileText className="w-3.5 h-3.5" />
            {isExporting ? "Exporting..." : "Download as PDF"}
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={exportToExcel}
            disabled={isExporting}
            className="h-8 px-3 text-xs gap-1.5 bg-white dark:bg-slate-800 border-slate-300 dark:border-slate-600 hover:bg-emerald-50 dark:hover:bg-emerald-900/30 hover:border-emerald-400 dark:hover:border-emerald-500 hover:text-emerald-700 dark:hover:text-emerald-300 transition-all"
          >
            <FileSpreadsheet className="w-3.5 h-3.5" />
            {isExporting ? "Exporting..." : "Download as Excel"}
          </Button>
        </div>
      </div>

      {/* Checklist items */}
      <div className="p-4">
        {hasCategories ? (
          <div className="space-y-6">
            {Object.entries(groupedItems.groups).map(
              ([category, categoryItems]) => (
                <div key={category}>
                  <h4 className="font-semibold text-xs text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2 px-3 flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-blue-500 dark:bg-blue-400" />
                    {category}
                  </h4>
                  <div className="space-y-1">
                    {categoryItems.map(renderChecklistItem)}
                  </div>
                </div>
              )
            )}
            {groupedItems.uncategorized.length > 0 && (
              <div>
                <h4 className="font-semibold text-xs text-slate-500 dark:text-slate-400 uppercase tracking-wider mb-2 px-3 flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-slate-400 dark:bg-slate-500" />
                  Other
                </h4>
                <div className="space-y-1">
                  {groupedItems.uncategorized.map(renderChecklistItem)}
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="space-y-1">{items.map(renderChecklistItem)}</div>
        )}
      </div>

      {/* Progress bar */}
      <div className="px-5 py-3 border-t border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800/30">
        <div className="flex items-center justify-between text-xs mb-1.5">
          <span className="text-slate-600 dark:text-slate-400 font-medium">
            Progress
          </span>
          <span className="text-blue-600 dark:text-blue-400 font-bold tabular-nums">
            {items.length > 0
              ? Math.round((checkedItems.size / items.length) * 100)
              : 0}
            %
          </span>
        </div>
        <div className="w-full h-2 bg-slate-200 dark:bg-slate-700 rounded-full overflow-hidden">
          <div
            className="h-full bg-gradient-to-r from-blue-500 to-indigo-500 rounded-full transition-all duration-500 ease-out"
            style={{
              width: `${items.length > 0 ? (checkedItems.size / items.length) * 100 : 0}%`,
            }}
          />
        </div>
      </div>
    </div>
  )
}
