import type { ScaleRoleKey } from "../scale"
// types implied via ExportInput
import { type ExportFile, type ExportInput, kebab } from "./types"

const ROLES: ScaleRoleKey[] = [
  "display",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "lead",
  "body",
  "small",
  "caption",
  "code",
]

/**
 * Design Tokens Community Group format (typography composite tokens).
 * Spec: https://tr.designtokens.org/format/#typography
 */
export function exportDTCG(input: ExportInput): ExportFile {
  const { name, tokens } = input
  const slug = kebab(name)

  const fontFamily = {
    sans: { $value: tokens.fonts.sans.split(/\s*,\s*/), $type: "fontFamily" },
    serif: { $value: tokens.fonts.serif.split(/\s*,\s*/), $type: "fontFamily" },
    mono: { $value: tokens.fonts.mono.split(/\s*,\s*/), $type: "fontFamily" },
    display: { $value: tokens.fonts.display.split(/\s*,\s*/), $type: "fontFamily" },
  }

  const typography: Record<string, unknown> = {}
  for (const role of ROLES) {
    const s = tokens.styles[role]
    typography[role] = {
      $type: "typography",
      $value: {
        fontFamily: `{fontFamily.${s.fontFamily}}`,
        fontSize: s.fontSize,
        fontWeight: s.fontWeight,
        lineHeight: s.lineHeight,
        letterSpacing: `${s.letterSpacingEm}em`,
      },
    }
  }

  const doc = {
    $schema: "https://schemas.designtokens.org/draft/2024-01/tokens.schema.json",
    $description: `${name} — generated by Accessible Typography Studio`,
    fontFamily,
    typography,
    paragraphSpacing: { $value: tokens.paragraphSpacing, $type: "dimension" },
    bodyMaxWidth: { $value: tokens.bodyMaxWidth, $type: "dimension" },
  }

  return {
    filename: `${slug}.typography.tokens.json`,
    language: "json",
    content: JSON.stringify(doc, null, 2) + "\n",
  }
}
