import type { ScaleRoleKey } from "../scale"
// types implied via ExportInput
import { type ExportFile, type ExportInput, kebab } from "./types"

const ROLES: ScaleRoleKey[] = [
  "display",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "lead",
  "body",
  "small",
  "caption",
  "code",
]

function pascal(name: string): string {
  return name
    .replace(/[-_]+(\w)/g, (_, c: string) => c.toUpperCase())
    .replace(/^[a-z]/, (c) => c.toUpperCase())
}

function fontWeightLiteral(w: number): string {
  if (w >= 800) return "FontWeight.ExtraBold"
  if (w >= 700) return "FontWeight.Bold"
  if (w >= 600) return "FontWeight.SemiBold"
  if (w >= 500) return "FontWeight.Medium"
  return "FontWeight.Normal"
}

export function exportKotlin(input: ExportInput): ExportFile {
  const { name, tokens } = input
  const slug = kebab(name)
  const namespace = pascal(slug) + "Type"

  const lines: string[] = [
    `// ${name} — generated by Accessible Typography Studio`,
    `package com.example.theme`,
    ``,
    `import androidx.compose.ui.text.TextStyle`,
    `import androidx.compose.ui.text.font.FontWeight`,
    `import androidx.compose.ui.unit.em`,
    `import androidx.compose.ui.unit.sp`,
    ``,
    `object ${namespace} {`,
  ]
  for (const role of ROLES) {
    const s = tokens.styles[role]
    const sizeSp = Math.round(s.fontSizePx.max * 100) / 100
    lines.push(`    val ${role} = TextStyle(`)
    lines.push(`        fontSize = ${sizeSp}.sp,`)
    lines.push(`        fontWeight = ${fontWeightLiteral(s.fontWeight)},`)
    lines.push(`        lineHeight = ${(sizeSp * s.lineHeight).toFixed(2)}.sp,`)
    lines.push(`        letterSpacing = ${s.letterSpacingEm}.em,`)
    lines.push(`    )`)
  }
  lines.push(`}`)

  return { filename: `${pascal(slug)}Type.kt`, language: "kotlin", content: lines.join("\n") + "\n" }
}
