import type { ScaleRoleKey } from "../scale"
// types implied via ExportInput
import { type ExportFile, type ExportInput, kebab } from "./types"

const ROLES: ScaleRoleKey[] = [
  "display",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "lead",
  "body",
  "small",
  "caption",
  "code",
]

function pascal(name: string): string {
  return name
    .replace(/[-_]+(\w)/g, (_, c: string) => c.toUpperCase())
    .replace(/^[a-z]/, (c) => c.toUpperCase())
}

function uiFontWeight(w: number): string {
  if (w >= 800) return "UIFont.Weight.heavy"
  if (w >= 700) return "UIFont.Weight.bold"
  if (w >= 600) return "UIFont.Weight.semibold"
  if (w >= 500) return "UIFont.Weight.medium"
  return "UIFont.Weight.regular"
}

export function exportSwift(input: ExportInput): ExportFile {
  const { name, tokens } = input
  const slug = kebab(name)
  const namespace = pascal(slug) + "Type"

  const lines: string[] = [
    `// ${name} — generated by Accessible Typography Studio`,
    "import UIKit",
    "",
    `enum ${namespace} {`,
  ]
  for (const role of ROLES) {
    const s = tokens.styles[role]
    const size = Math.round(s.fontSizePx.max * 100) / 100
    lines.push(
      `    static let ${role} = UIFont.systemFont(ofSize: ${size}, weight: ${uiFontWeight(s.fontWeight)})`
    )
    lines.push(
      `    static let ${role}LineHeight: CGFloat = ${(s.lineHeight * size).toFixed(2)}`
    )
  }
  lines.push("}")

  return { filename: `${pascal(slug)}Type.swift`, language: "swift", content: lines.join("\n") + "\n" }
}
